### ISSUE TITLE
[bug] Profil lycéen/Ma scolarité - En tant que lycéen en classe de Terminale, je peux partager une estimation de ma moyenne scolaire

### ISSUE THREAD

**Issue by Numero7** [betagouv/monprojetsup#10]
- n'apparaît que pour les lycéens de terminale
- possibilité bien explicite de ne pas renseigner la valeur (pour ne pas stresser). 
- checkbox "NSP (ne se prononce pas)" pour ne pas renseigner la valeur. Grise le composant.
- valeurs entre 0 et 20
- valeur par défaut à 14
- lors du changement de valeur, affichage dynamique d'un petit message du type "Tu t'es auto-évalué à  17/20. Parmi les lycéens de série de Bac 'Générale' admis dans une formation sur Parcoursup en 2023, 96 % avaient une moyenne générale inférieure ou égale à 17 ." (mesure autocensure pour les jeunes filles)
-  le choix de remplir ou ne pas remplir vient dans un second temps, ok en term eaccessibilité

**Comment by Maxgux** [comment]
En attente des deux tickets back lié à cette issue

**Comment by Maxgux** [comment]
Variable d'env feature flipping moyenne générale frontend

**Comment by Maxgux** [comment]
Pour recetter il faut rajouter au .env de son local dans app/front : VITE_FF_MOYENNE_GENERALE=true

Par défaut ce champ est caché si la variable d'env n'est pas définie

**Comment by Numero7** [comment]
nickel. On ressortira du placard après revalidation par les experts métiers et les beta-tests, en vérifiant que ça a une valeur ajoutée

**Comment by Numero7** [comment]
Deux demandes:

- [x] ajouter l'info sur la variable d'env dans le README (déjà dans le env.example)
- [x] après un tunnel d'inscription où VITE_FF_MOYENNE_GENERALE=falsse et le curseur n'apparaît pas, en db le profil a tout de même 14 dans le champs moyenne_generale. Il faudrait laisser à null ou une valeur signifiant "non-renseigné".

**Comment by Numero7** [comment]
c'est bon merci, -1 sur les nouveaux profils
