### ISSUE TITLE
Enregistrer les modifications du profil d'un lycéen

### ISSUE THREAD

**Issue by Maxgux** [betagouv/monprojetsup#138]
- Créer un endpoint POST /profil/ avec un body non optionnel
- Chacun des attributs du body est optionnel
- Tous les champs en BDD sont nullables et NULL par défaut ou [] pour les colonnes de type tableau
- Vérifier que les attributs ont des valeurs valides (si null les ignorer)
- Il faut renvoyer "non_communique" lors que l'élève a vu un champ mais qu'il a décidé de ne pas le remplir (champ optionnel)
- Enums des champs non présents en BDD : monprojetsup/app/front/src/features/élève/domain/élève.interface.ts
- Logger les erreurs (fichier log)
- Champs obligatoires: situation, classe, domaines, centresInterets, situationMetiers, situationVilles, situationFormations

Body 
```
{
    "situation": "aucune_idee",
    "classe": "terminale",
    "bac": "Générale",
    "specialites": [
      "1056",
      "1054"
    ],
    "domaines": [
      "T_ITM_1054",
      "T_ITM_1534",
      "T_ITM_1248",
      "T_ITM_1351"
    ],
    "centresInterets": [
      "T_ROME_2092381917",
      "T_IDEO2_4812"
    ],
    "situationMetiers": "quelques_pistes",
    "metiers": [
      "MET_123",
      "MET_456"
    ],
    "dureeEtudesPrevue": "options_ouvertes",
    "alternance": "pas_interesse",
    "situationVilles": "quelques_pistes",
    "villes": [
      {
        "codeInsee": "75015",
        "nom": "Paris",
        "latitude": 2.2885659,
        "longitude": 48.8512252
      }
    ],
    "moyenneGenerale": 14,
    "situationFormations": "quelques_pistes",
    "formations": [
      "fl1234",
      "fl5678"
    ]
}
```

**Comment by aureliadelzottoOCTO** [comment]
Situation metier formation et ville à challenger => est-ce qu'avoir la liste ne suffit pas ?

**Comment by Maxgux** [comment]
@aureliadelzottoOCTO nope il faut les deux car liste vide peut vouloir dire qu'il a des idées mais qu'il n'a rien renseigné c'est deux infos différentes

**Comment by Numero7** [comment]
@aureliadelzottoOCTO  @Maxgux  l'ajout de "formations" et "métiers" est mutualisable avec le endpoint "ajout favoris". Car côté métier c'est la même chose.

**Comment by Numero7** [comment]
fait doublon avec https://github.com/betagouv/monprojetsup/issues/141

**Comment by Maxgux** [comment]
Ok je ferme celui ci en faveur de l'autre, j'ai recopié les infos
