### ISSUE TITLE
Édition du profil d'un lycéen

### ISSUE THREAD

**Issue by Numero7** [betagouv/monprojetsup#141]
## Métier

- inclut ajout et suppression de favori #142

## Technique

- Créer un endpoint POST /profil/ avec un body non optionnel 
- Chacun des attributs du body est optionnel
- Tous les champs en BDD sont nullables et NULL par défaut
- Enums des champs non présents en BDD : monprojetsup/app/front/src/features/élève/domain/élève.interface.ts
- Logger les erreurs (fichier log)
- Champs obligatoires: situation, classe, domaines, centresInterets
- Si jamais erreur sur la désérialisation d'un enum, logguer une erreur et retourner 400 Bad request
- Vérifier que la moyenne_generale est entre 0 et 20 sinon 400
- Vérifier que la jointure entre baccalaureat et specialite est juste, si non, 400 Bad Request
- Vérifier que les attributs ont des valeurs valides et présentes en base sinon 400 (sauf communesFavorites, pas de check)
- Si la valeur est `null` l'ignorer
- Renvoie 204 avec empty body

## Body du POST
```
{
  "situation": "aucune_idee",
  "classe": "terminale",
  "baccalaureat": "Générale",
  "specialites": [
    "1056",
    "1054"
  ],
  "domaines": [
    "T_ITM_1054",
    "T_ITM_1534",
    "T_ITM_1248",
    "T_ITM_1351"
  ],
  "centresInterets": [
    "T_ROME_2092381917",
    "T_IDEO2_4812"
  ],
  "metiersFavoris": [
    "MET_123",
    "MET_456"
  ],
  "dureeEtudesPrevue": "options_ouvertes",
  "alternance": "pas_interesse",
  "communesFavorites": [
    {
      "codeInsee": "75015",
      "nom": "Paris",
      "latitude": 2.2885659,
      "longitude": 48.8512252
    }
  ],
  "moyenneGenerale": 14,
  "formationsFavorites": [
    "fl1234",
    "fl5678"
  ]
}
```

## NOTES Hugo
- Le référentiel des domaines pro et des centres d'intérêt n'est pas figé dans le temps, il peut évoluer. Il est possible qu'à un instant T on ajoute un centre d'intérêt puis à T+12 mois il disparait des référentiels de données.
- Une formation ou un métier est identifié par une string du type "fr12" ou "fl234" ou "met_123".
- Le référentiel des favoris est l'union du référentiel des métiers et de celui des formations.
- Le référentiel des favoris n'est pas figé dans le temps, il peut évoluer.
- Il est possible qu'à un instant T on ajoute un favori puis à T+3 mois ce favori disparait des référentiels de données formations et métiers.
- Cet endpoint est utilisé dans six contextes différents du front:
  - lors du parcours d'inscription, au moment de renseigner les métiers d'intérêt
  - lors du parcours d'inscription, au moment de renseigner les formations d'intérêt
  - sur l'écran d'exploration des suggestions de formations, possibilité d'ajouter une formation en favori
  - sur l'écran d'exploration des suggestions de formations, possibilité de supprimer une formation des favoris
  - lors de l'exploration des suggestions de formations, depuis la modale métier, possibilité d'ajouter un métier en favori
  - lors de l'exploration des suggestions de formations, depuis la modale métier, possibilité de supprimer un métier des favoris
  - lors de la consultation d'un favori, possibilité de le supprimer des favoris

**Comment by aureliadelzottoOCTO** [comment]
Challenge : Quel est l'utilité des champs `situation` comme `situationVilles`, `situationMetiers` et `situationFormations` ? Est-ce que une liste vide ou remplie n'équivaut pas à la donnée ?

**Comment by Maxgux** [comment]
> Challenge : Quel est l'utilité des champs `situation` comme `situationVilles`, `situationMetiers` et `situationFormations` ? Est-ce que une liste vide ou remplie n'équivaut pas à la donnée ?

utile (au moins côté front) car la situation est obligatoire, alors que donner la liste d'éléments ne l'est pas

**Comment by Maxgux** [comment]
@Numero7 un avis là dessus ?

**Comment by Numero7** [comment]
Du point de vue métier ça n'a pas vraiment de sens de stocker en db la réponse aux questions "as-tu déjà quelques idées de métiers" ou "Y a-t-il des études qui t'attirent ?". Car il se pourrait que pendant le tunnel le lycéen réponde "non" et "non" et ensuite il sélectionne des favoris ce qui modifie implicitement ses réponses en "oui".

Mais je comprends que côté front il ya  une différence entre "je n'ai jamais répondu à la question" et "ma réponse est non donc la liste est vide". Est-il possible de stocker les deux réponses aux deux questions dans la session du navigteur mais pas dans la db? Et de reposer systématiquement la question si on rerentre dans le tunnel et que la liste est vide (penser au cas potentiel de repassage dans le tunnel en début d'année).

**Comment by Maxgux** [comment]
Ok je vois le truc, je vais simplement en faire un toggle d'activation dans le processus d'inscription pour afficher ou masquer le champ de recherche métiers, formations ou villes. On ne le stock pas en bdd. Par contre on stock situation global sur le projet d'orientation non ? (j'ai une idée, j'ai aucune idée...) @Numero7 @aureliadelzottoOCTO

**Comment by Numero7** [comment]
@Maxgux  ok super pour le toggle d'activation. Oui on stocke situation globale, c'est précieux du point de vue métier pour suivre l'évolution chaque année.

**Comment by Maxgux** [comment]
@Numero7 j'y pense on peut questionner dans les maquettes le besoin de cliquer sur j'ai des idées en tête ou je ne sais pas si c'est juste pour afficher le champ de recherche des formations, recherche des métiers, ou villes. Si c'est une information qu'on ne stock pas je propose de la supprimer pour éviter un clic en moins à l'utilisateur et alléger grandement la logique côté front :)

Je vote pour !

**Comment by Numero7** [comment]
en fait on l'a ajouté car sinon problème d'ergonomie: on ne souhaite pas "forcer" les gens à ajouter  un métier ou une ville si ils n'ont pa d'idée  mais pour autant on en souhaite pas les laisser traverser à toute vitesse l'écran correspondant du tunnel sans se poser la question, comme Charlotte l'avait observé en tests qualis. Donc on les force à se positionner via cette question. Donc à garder stp. Après on est des mecs et des filles agiles donc si tu veux sauter rapidement par dessus cet obstacle alors il suffit de créer un ticket spécifique pour ne pas oublier, qu'on fera remonter le moment venu.

**Comment by Maxgux** [comment]
Ok je te propose un compromis j'ai supprimé celui sur les villes et gardé ceux de métiers et formations :)
Je pourrais t'expliquer de vive voix pourquoi. Je push les modifs en démo.
