### ISSUE TITLE
[FEEDBACK_PO] Tableau de bord / En tant que lycéen, je peux modifier mon profil

### ISSUE THREAD

**Issue by Numero7** [betagouv/monprojetsup#145]
- écran maquetés. 
- valeurs modifiables: scolarité / prefs études sup / domaines pro / centres d'intérêts

**Comment by Numero7** [comment]
Feedback: 
- [x] globalement nickel
- [x] deux premiers retours ci-dessous  à traiter avant ouverture aux beta-testeurs
- [x] dans les deux menus de sélection de catégorie supprimer le message "n'hésite pas à préciser les catégories" et remplacer par  le message de la maquette
- [ ] bug disparition des eds. Répétable. écran édition du profil. Changer/ajouter EDS. enregsitrer. Rafraichir la page. Modifier la valeur de "Classe actuelle". enregistrer. rafraichir. la liste des spécialités se vide (le POST part avec une liste vide de spécialités et les valeurs sont vidées en BDD)
- [ ] bug recherche de villes. Répétable. Après un rafraichissement de page, taper une lettre ou deux lettres affiche le message rouge "aucun résultat", il faut attendre la troisième lettre pour que le message d'erreur disparaisse. Préférer pas de message du tout ou alorsun message "mot trop court"
- [ ] bug les résultats de la recherhe de villes "nanntes, etc..." sont désynchronisés du contenu de la barre "bo" (cf copie d'écran). Tant que la troisième lettre n'est pas tapée, il semble que ce sont les résultats de la recherche précédente qui s'affichent.

### Détails "préciser les catégories"

message actuel

![Image](https://github.com/user-attachments/assets/5ad5f1b8-d44f-4337-97eb-fe9588af56a2)

message maquette

![Image](https://github.com/user-attachments/assets/e16714e6-a46a-46f5-b346-3b67977fb737)


### Détails "bug disparition des eds"

Avant le dernier rafraichir 


![Image](https://github.com/user-attachments/assets/49cba043-38d3-4e58-940b-fcc94c5350aa)

Après le dernier rafraichir 



![Image](https://github.com/user-attachments/assets/92e76fdf-69dc-4ad2-882b-d7627fcf5896)

### Détails bug recherche de ville "pas de réultat"



![Image](https://github.com/user-attachments/assets/30ffb760-5d4e-4f60-9ea5-d60ac9749002)

### Détails bug recherche de villes 2 "bo --> nantes"




![Image](https://github.com/user-attachments/assets/907d16d7-b894-4f1e-99ce-91d964344e91)

**Comment by Maxgux** [comment]
@Numero7 
- Je n'arrive pas à reproduire le bug de la recherche de la ville qui reste bloqué sur l'ancienne
- Pour le bug sur les eds qui disparaissent ce n'est pas un bug mais une feature. Si tu changes de bac le champ EDS est réinitialisé. C'était une discussion que nous avions en tout début de projet. Possible de changer le comportement, peut être via un nouveau ticket si ça te convient qu'on puisse le reprioriser individuellement.
- Le reste est résolu normalement :)

**Comment by Numero7** [comment]
@Maxgux 
* bug de la ville: je t'ai envoyé une démo vidéo par email
* eds qui disparaissent. C'est ok quand on change de bac, et d'ailleurs elles disparaissent immédiatement de l'écran, pas de souci et pas de surprise. Mais en changeant juste "classe actuelle" c'est plus compliqué car elles ne dispsraissent pas immédiatement de l'écran, ça n'est que en rafraichissant ou en revenant plus tard à l'onglet qu'on s'aperçoit qu'lles ont disparu. Comportmeent attendu: quand on change  "classe actuelle" sans changer "bac" alors les eds ne devraient pas disparaitre du tout.
* top pour le reste :-)

**Comment by Numero7** [comment]
Top

- bug eds --> solved
- bug ville --> solved à part encore un micro détail à régler, mais pas important, je fais un ticket à part
