### ISSUE TITLE
Fiche formation / En tant que lycéen, je peux visualiser les point d'affinité d'une fiche formation avec mon profil

### ISSUE THREAD

**Issue by Numero7** [betagouv/monprojetsup#149]
- maquetté
- fait partie des infos récupérées via le end point suggestions personnalsiées
- vision "nombre de points d'affinité dans la liste à gauche"
- vision "liste des points d'affinités" sur une card

- les points d'afffinités incluent, par ordre décroissant d'intérêt métier
- [ ] [IMPORTANT] centres d'intérêts et domaines pros
- [ ] [IMPORTANT] type de bac
- [ ] [IMPORTANT] villes
- [ ] [MEDIUM] similarité avec formations similaires
- [ ] [MEDIUM] cohérence intérêt pour alternance études
- [ ] [MEDIUM] cohérence durée études
- [ ] [MEDIUM] cohérence spécialités
- [ ] [LUXE] cohérence moyenne générale auto évaluée

**Comment by Maxgux** [comment]
Je fusionne avec une autre
