### ISSUE TITLE
[FEEDBACK_PO] Métiers / En tant qu'utilisateur, je peux consulter le détail d'un métier sous forme de modale

### ISSUE THREAD

**Issue by Numero7** [betagouv/monprojetsup#156]
- maquetté https://www.figma.com/design/oXT35cxqKWY168pQBVgixB/MonProjetSup?node-id=1764-499066&m=dev
- utilisation lors de l'exploration, depuis une fiche formation
- Afficher le nom du métier
- Afficher la description
- Afficher la liste de liens associés

**Comment by Numero7** [comment]
PO feedback
- [x] bon en l'état pour les beta-tests
- [x] ce serait mieux que le clic sur un lien externe ouvre sur un nouvel onglet, sinon gros coût pour l'utilisateur quand il clique sur un lien externe, car pour revenir sur MPS il doit cliquer sur le bouton "back" fait revenir sur le menu initial de l'exploration en perdant tout le contexte: la formation n'est plus sélectionnée et la modale métier a disparu. Patch alternatif à l'ouverture dans un nouvel onglet: le bouton back permet de revenir exactement dans le mêm contexte avec la même formation sélectionnée et le modale métier ouverte.

**Comment by Maxgux** [comment]
Ok j'ai fait ouvrir tous les liens externes vers une nouvelle fenêtre

**Comment by Numero7** [comment]
Nickel
