### ISSUE TITLE
Métiers / en tant qu'utilisateur, je peux consulter un métier sous forme de fiche

### ISSUE THREAD

**Issue by Numero7** [betagouv/monprojetsup#157]
- maquetté https://www.figma.com/design/oXT35cxqKWY168pQBVgixB/MonProjetSup?node-id=1779-545861&m=dev
- utilisation depuis écran des favoris
- texte
- lien vers fiche complète
- deux boutons favoris
- exemples de formations

**Comment by Maxgux** [comment]
@Numero7 J'ai du adapter un peu le design pour des questions de rapidité de dev et de mutualisation des composants. Si c'est choquant on en reparle :)

**Comment by Numero7** [comment]
nickel, merci
