### ISSUE TITLE
Liste formations / En tant qu'utilisateur, je peux rechercher une formation

### ISSUE THREAD

**Issue by Numero7** [betagouv/monprojetsup#160]
- maqueté https://www.figma.com/design/oXT35cxqKWY168pQBVgixB/MonProjetSup?node-id=413-45530&m=dev
- Chercher une formation via la barre de recherche de l'écran exploration
- fait appel au endpoint #133

**Comment by Numero7** [comment]
- [x] bug envoyé par email: recherche sur "PASS", la liste se met à jour , clique sur "PASS", la formation est affichée mais la liste se modifie
- [x] un clic sur un élément de a liste vide le champ recherche
- [x] une nouvelle recherche ne réinitialise pa sla fiche de droite, aon arrive dans des états bizarre (cf copie écran ci dessous), ce serait mieux que une nouvelle recherche avec rafraichissement de liste le premier résultat soit automatiquement sélectionné. Exemple "cheval" amène à une liste à un seul élément "bpjeps" mais je garde "L1 maths accès santé" en fiche à droite.
- [x] à mi-chemin de la liste, une nouvelle recherche suivi de "entrée" ne fait pas remonter dans la liste, on reste au milieu, ce serait mieux de remonter en tête de liste afin de visualiser les résultats les plus pertinents (wanabee) en premier 

![Image](https://github.com/user-attachments/assets/26258575-6556-4ecc-aba8-714ff25f583f)

**Comment by Maxgux** [comment]
Ok j'ai effectué les corrections :)

**Comment by Numero7** [comment]
j'ai tout retesté c'est nickel je passe en DONE
