### ISSUE TITLE
mode "dev"  permettant de faire tourner back + front sans internet

### ISSUE THREAD

**Issue by Numero7** [betagouv/monprojetsup#169]
- un keyclock local est lancé via docker compose sur le profil dev

**Comment by Numero7** [comment]
feedback
* "docker compose -f docker-compose.dev.yml up" --> semble ok. Mais le navigateur refuse d'afficher http://localhost:5003, "le serveur a inopinément terminé la connection"
* dans app/back/README.md je n'ai pas trouvé d'instructions pour lancer le back, seulement des instructions et infos concernant les variables d'env
* dans app/front/README.md il faut préciser que "npm install" doit être exécuté avant le premier lancement de "npm "run dev"
* après avoir lancé "npm run dev", la page http://localhost:5001 est totalement blanche sans message d'erreur. La console js du navigateur indique 
* 

![Image](https://github.com/user-attachments/assets/ec891e89-7ad7-4d60-aaa2-cef624126621)

**Comment by Maxgux** [comment]
Ok c'est corrigé
