### ISSUE TITLE
Recherche de métiers

### ISSUE THREAD

**Issue by aureliadelzottoOCTO** [betagouv/monprojetsup#174]
_En tant que lycéen
Je veux pouvoir chercher un métier à l'aide de son label et sa description
Afin de faire mes recherche_

## Description du ticket
Chercher une string parmi les métiers

## Métier
Utilisé dans le parcours d'inscription, pour choisir les métiers d'intérêts

## Règles métiers
- En premier prendre en compte le label, puis la description
- Être agnostique au niveau des accents et majuscules

## Technique
- Créer le endpoint GET /métier/recherche/succincte avec @QueryParam `recherche` qui est une String. Renvoie tableau de métiers avec leur id et libelle

**Comment by Numero7** [comment]
feedback

- 'tennis' renvoie "entraîneur / entraîneuse de chevaux" https://api-mps.avenirs.onisep-preprod.fr/api/v1/metiers/recherche/succincte?recherche=tennis => à cause du descriptif qui commence par "À l'image d'un Guy Forget pour le tennis ou d'un Laurent Blanc pour le football"

**Comment by Numero7** [comment]
ok ça explique bien

Si c'est pas encore le cas, peux-tu prioriser dans la liste les résultats qui matchent sur le titre devant ceux qui  matchent sur le descriptif?
