### ISSUE TITLE
Recherche succincte de formations

### ISSUE THREAD

**Issue by aureliadelzottoOCTO** [betagouv/monprojetsup#196]
_En tant que lycéen
Je veux pouvoir chercher une formation à l'aide de mot clé
Afin de faire mes recherche_

## Description du ticket
Chercher un mot clés parmi les formations

## Métier
GET /formations/recherche/succincte => Utilisé dans le parcours d'inscription, pour choisir les formations d'intérêts
Si l'utilisateur cherche un métier, alors on retourne les formations associées (les métiers seront ajoutés comme mot-clés en BDD par l'ETL)

## Règles métiers
- En premier prendre en compte le titre, puis les mots clés
- Être agnostique au niveau des accents et majuscules

## Technique
- Créer le endpoint GET /formations/recherche/succincte avec @QueryParam `recherche` qui est une String. Renvoie tableau de formations détaillés

**Comment by Numero7** [comment]
feedback


Dans plein de cas c'est nickel comme par exemple 'BUT' 'ingénieur' 'PASS' 'PCSI' etc...

Quelques cas limites à regarder pour comprendre

[VUS]
- pourquoi "L1 maths" matche sur "MPSI" https://api-mps.avenirs.onisep-preprod.fr/api/v1/formations/recherche/succincte?recherche=mpsi. C'est dans les mots-clés
- sur "professeur" réponse bizarre: une seule formation et pas la plus pertinente --> @Numero7 enrichit les mots-clés avec les métiers associés
- sur "designer" on a "L1 - Musicologie -  Accès Santé (LAS)"- {
      "id": "fl2072",
      "nom": "L1 - Etudes théâtrales"
    },
- sur "médecin" PASS ne remonte pas dans les premières réponses https://api-mps.avenirs.onisep-preprod.fr/api/v1/formations/recherche/succincte?recherche=m%C3%A9decin --> @Numero7 PASS devrait remonter en premier mais pourquoi? Inventer une règle...

[ÈN COURS]

- insensibilité aux accents et aux capitalisation / majuscule. Exemples d'effets de bords
- on a pas "sciences po" sur "sciences po" https://api-mps.avenirs.onisep-preprod.fr/api/v1/formations/recherche/succincte?recherche=sciences%20po. PAr contre sur "Sciences Po". De plus fl810018 sort en ^premier.

- un peu n'importe quoi sur "BTs adudiovisuel" https://api-mps.avenirs.onisep-preprod.fr/api/v1/formations/recherche/succincte?recherche=BTs%20adudiovisuel. --> @Numero7  faire un ticket sur robiustesse aux erreurs de frappe

- sur 'las' la première réponse est une CPES https://api-mps.avenirs.onisep-preprod.fr/api/v1/formations/recherche/succincte?recherche=LAs mais sur LAS
