### ISSUE TITLE
en tant que lycéen, je peux sélectionner des voeux associés à un de mes favoris

### ISSUE THREAD

**Issue by Numero7** [betagouv/monprojetsup#220]

**Comment by Numero7** [comment]
Maquette https://www.figma.com/design/oXT35cxqKWY168pQBVgixB/MonProjetSup?node-id=2865-56653&t=3flKNZky6BTUIg3O-4

Le lycéen peut choisir les établissements dans lesquels il prévoit de candidater.

Les établisements sont en fait indexés sur les voeux parcoursup, identifiés par les triplets d'affectation g_ta_cod

**Comment by Maxgux** [comment]
Limite pour le champ libre : 4000 caractères

**Comment by Maxgux** [comment]
J'ai lutté pendant longtemps contre un bug présent dans le DSFR. qui fait que les onglets n'ont pas forcément une hauteur correctement calculée au chargement du composant. C'est un cas présent uniquement en responsive et pour des conditions spécifiques. Je met de côté pour le moment mais je suis au courant et je regarderais une fois que j'aurais terminé la feature

**Comment by Numero7** [comment]
Tout d'abord: GENIALLLLLLLLLLLLLL !!!!!!!!! Trop content de voir cette fonction!!!!!! Et en plus ça tombe à point nommé avant le début des beta-tests donc nickel.

bien vu pour le bug DSFR, bon courage pour résoudre ça.

Feedback: 
- [x] quand la liste comporte + de 5 éléments (tester sur "BTS MCO" à Paris), possible d'afficher 5 éléments + "Voir davantage d'établissements..." pour dérouler le reste? Comme dans "lire la suite / masquer la suite" pour le texte.
- [x] [ ] le click sur "[Préférences de villes](http://localhost:5001/profil)" amène bien à "Mon profil" mais pas sur le bon onglet (Safari, pas dramatique, on peut mettre en standby)

**Comment by Numero7** [comment]
super, gros morceau dépilé
