### ISSUE TITLE
La redirection après la connexion fonctionne de manière aléatoire

### ISSUE THREAD

**Issue by Maxgux** [betagouv/monprojetsup#231]

**Comment by Maxgux** [comment]
Kaliop doit changer les Valid redirect URIs pour rajouter /*

**Comment by Maxgux** [comment]
Pour recetter en local il faut, supprimer le dossier keycloak/db puis relancer les container docker de la bdd keycloak puis relancer keycloak

**Comment by Numero7** [comment]
je ne parviens plus à reproduire le problème!me sur https://app-mps.avenirs.onisep-preprod.fr/
