### ISSUE TITLE
[FEEDBACK_PO] Modifier formationHttpRepository pour ne plus prendre en compte le taux d'affinité mais plutôt calculer les points d'affinité

### ISSUE THREAD

**Issue by Maxgux** [betagouv/monprojetsup#236]
ait partie des infos récupérées via le end point suggestions personnalsiées

vision "nombre de points d'affinité dans la liste à gauche"

vision "liste des points d'affinités" sur une card

les points d'afffinités incluent, par ordre décroissant d'intérêt métier

[IMPORTANT] centres d'intérêts et domaines pros

[IMPORTANT] type de bac

[IMPORTANT] villes

[MEDIUM] similarité avec formations similaires

[MEDIUM] cohérence intérêt pour alternance études

[MEDIUM] cohérence durée études

[MEDIUM] cohérence spécialités

[LUXE] cohérence moyenne générale auto évaluée

**Comment by Numero7** [comment]
@Maxgux c'est une demande front ou back?

Côté front dans la recette actuellement, l'ordre hiérarchique n'est pas respecté.

Tu veux que je fasse évoluer l'api suggestion pour que l'ordre soit fixé dans le back? 



![Image](https://github.com/user-attachments/assets/c8052d09-c34b-4d54-b1fa-06db738e9bd5)

**Comment by Maxgux** [comment]
@Numero7 Oui c'est un calcul qui se fait côté front. J'ai changé l'ordre de mon côté

**Comment by Numero7** [comment]
@Maxgux sur démo j'ai encore les mots-clés en dernier alors qu'ils sont noramelement dans la catégorie "important" donc en premier?

**Comment by Numero7** [comment]
je reformule "mots-clés " --> "centres d'intérêts et domaines pros"

**Comment by Numero7** [comment]
La dernière explication serait mieux en premier dans la liste, c'est le plus "obvious"

![Image](https://github.com/user-attachments/assets/05508eec-1bb8-44d7-abc5-90a8788c04e7)

**Comment by Numero7** [comment]
nickel
