### ISSUE TITLE
Fixer swagger pour que le profil exemple fonctionne

### ISSUE THREAD

**Issue by aureliadelzottoOCTO** [betagouv/monprojetsup#246]
- donner des spécialité accordées au baccalauréat
- remplacer les intérêt par les nouveaux codes

**Comment by Numero7** [comment]
@aureliadelzottoOCTO tu as en tête le swagger du back ou de l'API suggestions? C'est pour toi ou pour moi?

**Comment by Numero7** [comment]
@aureliadelzottoOCTO ok j'ai compris 
nickel
