### ISSUE TITLE
Corrections accessibilité

### ISSUE THREAD

**Issue by Maxgux** [betagouv/monprojetsup#251]
- [X] Liens d'évitement sans ancre focus JS
- [x] Liens d'évitement pour le détail d'une formation sans ancre focus JS
- [x] Double navigation (plan de site)
- [x] Proposer une alternative (ne pas faire passer l'info que par la couleur ou la forme)
- [ ] Regrouper les champs qui intéragissent entre eux dans des fieldset
- [x] Changer les urls de formation pour utiliser des # 
- [x] Liste des résultats sous forme de lien
- [x] Passer les br en role presentation
- [x] Remettre le focus lors de la selection d'une suggestion

**Comment by Maxgux** [comment]
@Numero7 tout ok sauf les fieldset

**Comment by Numero7** [comment]
fieldset dabs le backelog
