### ISSUE TITLE
[BUG] tunnel inscription: "as-tu déjà quelques idées de métiers" n'est pas obligatoire

### ISSUE THREAD

**Issue by Numero7** [betagouv/monprojetsup#266]
dans le tunnel, écran "As-tu déjà quelques idées de métiers ?"

en cliquant sur 'j'ai identifié quelques idées de métiers" puis en n'utilisant pas le moteur de recherhe ou en ne sélectionant pas de métier, on peut passer à l'écran suivant puis revenir et on se retrouve dans un état bizarre où aucune des deux cases de réponse n'est cochée mais on peut tout de meêm poursuivre le tunnel 

Comportement attendu: si "j'ai quelques idées d métier" est cliqué mais aucun métier n'est sélectionné alors on ne peut pas passer à l'écran suivant.

![Image](https://github.com/user-attachments/assets/5c888dfc-e090-49d3-b8fb-fa1e96fcb8a4)

**Comment by Maxgux** [comment]
Ok c'est potentiellement gérable mais c'est un cas très à la marge à mon sens. Je propose de le prioriser tout en bas de la TODO.

**Comment by Numero7** [comment]
nickel merci
