### ISSUE TITLE
[BUG] Les explications ne sont pas toujours correctement retournées

### ISSUE THREAD

**Issue by Maxgux** [betagouv/monprojetsup#270]
Pour reproduire créer un profil et lui renseigner des domaines activité ou centres interets mais ne pas renseigner le champ bac. Puis voir les suggestions. pas d'explications

Ensuite lui rajouter un bac général par exemple et demander à nouveau les suggestions. des explications apparaissent en plus du bac sur les domaines et centres d'intêret

**Comment by Numero7** [comment]
@aureliadelzottoOCTO je regarde

**Comment by Numero7** [comment]
@Maxgux  je ne parviens pas à reproduire le bug, cf copies d'écran ci-dessous.

Tu saurais récupérer le contenu de la requête qui est envoyée au back?

![Image](https://github.com/user-attachments/assets/e1e625df-da97-4374-8e85-9d848da3833f)



![Image](https://github.com/user-attachments/assets/39bbf8a6-add0-4d20-a880-4a18c5dc6557)
