### ISSUE TITLE
Gérer l'indisponibilité des serveurs 

### ISSUE THREAD

**Issue by Numero7** [betagouv/monprojetsup#271]
Quand le serveur de suggestions est injoignable, cela provoque l'erreur suivante.
Ce serait mieux d'avoir une liste vide, sans message d'erreur.

![Image](https://github.com/user-attachments/assets/07fc6f85-deec-432d-b87f-698c66234224)

**Comment by Maxgux** [comment]
Compliqué comme bug, car cette url n'est là que pour rediriger l'utilisateur vers sa première suggestion. J'ai donc besoin de cet appel  et de cet id.

**Comment by Numero7** [comment]
Faisable de vérifier que le tableau est vide et si c'est le cas  rediriger vers le tableau de bord plutôt que l'écran d'exploration?

**Comment by Maxgux** [comment]
"ce serait mieux que l'appel à l'API échoue et/ou qu'il y ait un message côté front "problème technique en cours de résolution" + redirection vers le tableau de bord"

**Comment by Maxgux** [comment]
Afficher un message "maintenance en cours" si la réponse aux appels api est 50*

**Comment by Numero7** [comment]
nickel merci
