### ISSUE TITLE
retour utilisateur en cas de panne de l'API suggestions

### ISSUE THREAD

**Issue by Numero7** [betagouv/monprojetsup#287]

**Comment by Numero7** [comment]
Si le serveur de suggestions est down, l'utilisateur voit ce message



![Image](https://github.com/user-attachments/assets/62337184-b53c-401d-bc93-45b9a80485e8)

ce serait mieux que l'appel à l'API échoue et/ou qu'il y ait un message côté front "problème technique en cours de résolution" + redirection vers le tableau de bord

**Comment by Maxgux** [comment]
Je fusionne avec la #271
