### ISSUE TITLE
réduire le nombre minimal de spécialités  à une au lieu de deux

### ISSUE THREAD

**Issue by Numero7** [betagouv/monprojetsup#303]
en terminale STMG en pratique une seule spécialité est demandée

modification proposée: réduire pour tous les bacs le nombre minimal de spécialités à une au lieu de deux

**Comment by Maxgux** [comment]
@Numero7 Il n'y a pas de nombre minimal de spécialité requis quand on sélectionne un bac

**Comment by Numero7** [comment]
@Maxgux bien vu, tu peux oublier :-)
