### ISSUE TITLE
ajouter un sentry

### ISSUE THREAD

**Issue by Numero7** [betagouv/monprojetsup#343]

**Comment by Maxgux** [comment]
J'attends l'ajout des variables d'env de AB mais ok de notre côté le code est poussé

**Comment by Numero7** [comment]
@Maxgux comment puis-je tester?

**Comment by Numero7** [comment]
si c'est ok pour toi alors ferme le ticket. On va continuer à avoir un résumé hebdo ou c'était sur l'offre cloud?

**Comment by Numero7** [comment]
@Maxgux nickel merci
