### ISSUE TITLE
Créer une table des voeux à x km d'une commune

### ISSUE THREAD

**Issue by Numero7** [betagouv/monprojetsup#371]
- [x] Hugo;: ajouter une table dans l'etl avec les paires commune + liste de triplets d'affecttaion à moins de 10km
- [ ] Aurelia: insère les données pertinentes dans l'API back

**Comment by Numero7** [comment]
@aureliadelzottoOCTO j'ai créé la table qui contient les données (ref_join_ville_formation). Peux tu stp passer au front les infos 10km et 30km dans deux tableaux séparés? Car on va probablement faire remonter les deux dans le front

**Comment by Numero7** [comment]
@Numero7 inclure les vrais distances

**Comment by Numero7** [comment]
@aureliadelzottoOCTO c'est fait côté etl  https://github.com/betagouv/monprojetsup/blob/demo/app/etl/etl-common/src/main/kotlin/fr/gouv/monprojetsup/data/formation/entity/VilleVoeuxEntity.kt

**Comment by aureliadelzottoOCTO** [comment]
Copié ici https://github.com/betagouv/monprojetsup/issues/404
