### ISSUE TITLE
Ouvrir les endpoints actuellement réservés aux élèves aux profils profs et experts également

### ISSUE THREAD

**Issue by Maxgux** [betagouv/monprojetsup#374]
## Description
_En tant que professeure ou expert, 
Je souhaite accéder à la même interface que les élèves
Afin de tester avec mon compte la plateforme_

## Règles métiers
- Les même règles que pour un élève

## Implémentation 
- Créer une colonne avec type_profil qui peut contenir un enum "ELEVE", "ENSEIGNANT" ou "EXPERT"
- Ouvrir les endpoints de /profil à tous
- Utiliser le pseudo profil pour les suggestions et renvoyer des fiches pour un profil
- On laisse la table nommer à l'identique car vocation à disparaitre ?
- Quid des objets `FicheSansProfil` ? Les garder pour le partage des fiches par url ?

**Comment by Numero7** [comment]
nickel, fonctionne en preprod
