### ISSUE TITLE
affichage de NC dans les stats d'admission

### ISSUE THREAD

**Issue by Numero7** [betagouv/monprojetsup#377]
![Image](https://github.com/user-attachments/assets/0557b2a9-399e-4f46-9046-06e3ecd14fa3)

**Comment by Numero7** [comment]
@aureliadelzottoOCTO tu peux étudier pour voir comment ça peut ariver, il faut changer qq chose dans etl ou dans back?

**Comment by aureliadelzottoOCTO** [comment]
@Numero7 
J'ai l'impression que c'est côté BDD, y a une donnée NC dans la BDD, qui semble correspondre au total des autres (donc fréquence de tout bac confondu)

![Image](https://github.com/user-attachments/assets/33293a8b-cda7-44b6-9a6f-e28f51f0d1b9)

Je me demande un peu à quoi elle sert du coup ?

**Comment by Numero7** [comment]
Elle me sert de stat aggrégée "TOUS_BACS", par exemple pour les lycéens qui n'ont pas précisé leur type de bac, ou un type de bac bizarroide, elle est présente dans toutes les stats. Tu peux l'ignorer stp dans tes appels côté back?

**Comment by Numero7** [comment]
bye bye le bac de Nouvelle-Calédonie
![Image](https://github.com/user-attachments/assets/b9ce9a27-fc90-4d21-b8d2-54303afdc3d2)

nickel merci
