### ISSUE TITLE
personnaliser message d'accueil en fonction du niveau

### ISSUE THREAD

**Issue by Numero7** [betagouv/monprojetsup#388]
![Image](https://github.com/user-attachments/assets/59808ea6-7271-4e8e-a82e-b3f90df05d1e)

**Comment by Maxgux** [comment]
On supprime ce ticket du coup ?

**Comment by Numero7** [comment]
non on le garde mais il était dans la mauvaise colonne, je l'ai remis en backlog PO,

**Comment by Numero7** [comment]
abandonné remplacé par les 6 niveaux
