### ISSUE TITLE
beta.monprojetsup.fr

### ISSUE THREAD

**Issue by Numero7** [betagouv/monprojetsup#39]
Priorisation en trois groupes.
Les items checkés ont été traités. 

Groupe A (prioritaire)

- [x] la recherche sur "vétérinaire" doit renvoyer en premier sur "écoles vétérinaires"
- [x] Landing Page  - A - Le visuel de Landing page n’est pas à jour (contenus et visuels)
- [x] Landing Page - A - est-il possible de ne pas rendre cliquable le bouton se connecter ?
- [x] Ma scolarité - Le wording sur les EDS n’est pas le bon > à remplacer par : Spécialités (EDS) choisies ou envisagées
- [x] tabs sur détails formation y compris critères
- [x] Dans les formations sélectionnées, les boutons des "Exemples de métiers accessibles après cette formation" ne sont pas cliquables
- [x] A propos des études supérieures - Avant cet écran, il manque l’écran « Les métiers qui m’inspirent »
- [x] A propos des études supérieures - Après cet écran, il manque l’écran « Les études ou cursus qui t’attirent »
- [x] curseur auto évaluation scolarité
- [x] ajout des écrans profs
- [x] importer les émojis de Lauriane sur les groupes thématiques
- [x] afficher les villes même si pas de préférence sgéos
- [x] éviter de proposer CPGE si 12 de moyenne
- [x] CPES éco-social remonte trop avec trop de métiers
- [x] trop de formations avec descriptifs vides. Exemple: Cycle pluridisciplinaire d'Études Supérieures - Sciences
- [x] masquer la box "affiche ta sélection" si sélection vide
- [x] ajouter à la corbeille
- [x] gros message rouge  et input rouge si pas de correspondance
- [x] barre recherche  en sticky
- [x] affinité max à 90%
- [x] au moins un domaine pro
- [x] au moins deux EDS si premiere ou terminale
- [x] oubli mdp
- [ ] vue synthétique des sélections
- [x] raccourcis depuis homepage

Groupe B (important)

- [x] Mon projet supérieur - B - Il y a un point en trop dans les sous-textes des 2 propositions du bas (quelques pistes d’orientation et projet précis)
- [x] Domaines professionnels - B - Les catégories doivent apparaitre par ordre alphabétique pour faciliter la lecture
- [x] Domaines professionnels - B - Les intitulés des sous-catégories ne correspondent pas à ce qui apparait sur les maquettes de Nico
- [x] Centres d’intérêts - B - Les intitulés des catégories et sous-catégories ne correspondent pas à ce qui apparait sur les maquettes de Nico
- [x] Inscription -  Il manque la barre de progression
- [x] Domaines professionnelss - B - Il faudrait qu'il n'y ait qu'un seul émoji au niveau de la catégorie principale (à date, il y en a autant que de sous-catégories)
- [x] ne pas afficher "nos conseils" si rubrique vide
- [ ] dico synonyme entre directeur et manager
- [x] réduire espace entre  champ recherche EDS et liste des EDS
- [x] incorporer les acronymes d'EDS dans la liste
- [x] ajouter l'EDS AMC (anglais monde contemporain)
- [x] BPJEPS voile nautique s'affiche, et mène à voile
- [x] le prof peut soutenir un choix et commenter
- [ ] côté prof: à qui cette formation devrait plaire ?
- [x] masquer eval aux terminales

Groupe C (luxe)

- [x] Études supérieures → Durée des études → L'une des 3 propositions n'a pas de point.
- [x]  Dans "Plus tard, je voudrais..." → est-ce qu'il n'y a pas un échange d'emojis entre les deux sous-cat de Transmettre et s'occuper des plus jeunes ?
- [x] Rejoindre MPS - C -  Il n’y a pas  le sous-texte sur le code d’accès
- [x] Créons ensemble votre profil - C - Il manque la case sur les conditions générales d’utilisation de MPS
- [x] A propos des études supérieures - C - Il n’y a pas les 2 options sous « où souhaites-tu étudier? »
- [x] masque nb lycéens si non défini
- [x] supprimer le terme "EDS"
- [x] menu sélection visible ssi au moins un favori

Groupe Z (hors backlog de beta.mps)
- [x] Landing Page    - B - au clic sur Créer mon compte et au clic sur Commencer l’inscription, est-il possible d’arriver directement sur l’écran Rejoindre MPS ?
- [ ] Créons ensemble votre profil - C - Il n’y a pas la possibilité de choisir email ou pseudo (seulement identifiant)
- [ ] Inscription - C -  Il n’y a pas la mention * sur les champs obligatoires

**Comment by clembiffaud** [comment]
moved in the task list

**Comment by charlottelecuit** [comment]
moved in the task list
