### ISSUE TITLE
bouton fermer sur la modale des métiers

### ISSUE THREAD

**Issue by Numero7** [betagouv/monprojetsup#421]
https://www.figma.com/design/oXT35cxqKWY168pQBVgixB/MonProjetSup?node-id=1764-499066&t=SVh0clVyZBTzCcQm-4

Entête.tsx
ProfilÉlève.tsx
useUtilisateur.ts

**Comment by Maxgux** [comment]
![Image](https://github.com/user-attachments/assets/1935e1ab-e2a6-4170-b6ac-bff3d455acd7)

**Comment by Numero7** [comment]
nickel, merci
