### ISSUE TITLE
spécifier systématiquement si une formation est dispo en alternance

### ISSUE THREAD

**Issue by Numero7** [betagouv/monprojetsup#422]
https://www.figma.com/design/oXT35cxqKWY168pQBVgixB/MonProjetSup?node-id=413-45530&t=SVh0clVyZBTzCcQm-4

**Comment by Maxgux** [comment]
On le fait ça du coup c'est sec?

**Comment by Numero7** [comment]
oui c'est bon, vu avec Nico

**Comment by Numero7** [comment]
nickel merci
