### ISSUE TITLE
Matomo

### ISSUE THREAD

**Issue by Maxgux** [betagouv/monprojetsup#444]
Ticket côté Kaliop https://jira-kaliop.atlassian.net/browse/ONISEPBLD-210

**Comment by Maxgux** [comment]
ce serait bien d'avoir en bdd la liste des recherches effectuées par les utilisaturs de MPS

**Comment by Maxgux** [comment]
@Numero7 On défini quoi comme plan de taggage?

**Comment by Numero7** [comment]
tu m'explique la question dans 5 minutes :-)

**Comment by Numero7** [comment]
@Maxgux 
proposition plan de taggage:

- changements de vue "tableau de bord" / "sélection" / "édition de profil"
- recherche y compris  terme de recherche
- click sur une fiche formation
- ajout en favori formation
- ajout en favori métier
- auto évaluation niveau ambition
- click sur "dis nous en plus"
- click sur les différents onglets du choix d'établissement (nantes / paris / toutes villes)
- ajout établissement

**Comment by Maxgux** [comment]
Je n'ai toujours pas de matomo car AB n'a pas la bande passante

**Comment by Numero7** [comment]
ok on part sur le matomo beta.gouv dans un premier temps

**Comment by Maxgux** [comment]
@Numero7 on reparle vendredi pour voir comment recetter

**Comment by Numero7** [comment]
ajouter deux évènement stp 

ajout en favori formation
ajout en favori métier


(+ state qui pollue)

**Comment by Maxgux** [comment]
Ok c'est en cours de déploiement + suppression du tracking uat utilisé sur preprod

**Comment by Numero7** [comment]
Super. Autre chose

J'aimerais bien le partager avec des gens qui n'ont pas vocation à avoir un compte sur stats.beta.gouv.fr. Pourrais-tu te renseigner auprès de Denis ou communauté beta/.gouv pour savoir comment rendre nos stats publiques, par exemple en les rendant accessibles via le menu déroulant quand on arrive sur la page https://stats.beta.gouv.fr/i sans être connecté?

![Image](https://github.com/user-attachments/assets/17691765-1b2c-455c-8d6b-c51180710087)

@Maxgux

**Comment by Numero7** [comment]
public
