### ISSUE TITLE
Ajouter les liens du footer vers les pages légales

### ISSUE THREAD

**Issue by Maxgux** [betagouv/monprojetsup#445]
Plan du site : créer la page
Accessibilité : non conforme : créer la page (s'inspirer de https://design.numerique.gouv.fr/outils/exemple-declaration-accessibilite/)
Mentions légales : https://monprojetsup.fr/mentions-legales/
Données personnelles : https://monprojetsup.fr/donnees-personnelles/

**Comment by Numero7** [comment]
ok merci
