### ISSUE TITLE
ajouter un métier à mes favoris

### ISSUE THREAD

**Issue by Numero7** [betagouv/monprojetsup#502]
Pouvoir rechercehr manuellement un métier et l'ajoute r à ses favoris.

dupliquer le menu du tunnel "métiers favoris" dans l'édition du profil

maquetté: https://www.figma.com/design/oXT35cxqKWY168pQBVgixB/MonProjetSup?node-id=4604-40548&t=yo3m8cls1Lxhj2i0-4

**Comment by Maxgux** [comment]
Doublon avec le #535 il me semble

**Comment by Numero7** [comment]
ok je clos
