### ISSUE TITLE
bug clignotement sélection / désélection métiers

### ISSUE THREAD

**Issue by Numero7** [betagouv/monprojetsup#602]
Un bug front bizarre quand on sélectionne / déselectionne des métiers,
ça semble « clignoter »,
difficile à expliquer,
j’ai fait une vidéo via email.

**Comment by Maxgux** [comment]
Je n'arrive pas à reproduire @Numero7

**Comment by Numero7** [comment]
@Maxgux je ne reproduis que en local, à la fois sous safari et firefox. Je te fais une démo maintenant si tu veux?

**Comment by Numero7** [comment]
@Maxgux je reprends la main pour diagnostiquer ça en local

**Comment by Numero7** [comment]
non reproductible
