### ISSUE TITLE
rendre chaque voeu Parcoursup sélectionné clickable

### ISSUE THREAD

**Issue by Numero7** [betagouv/monprojetsup#619]
front: maquetté ici: https://www.figma.com/design/oXT35cxqKWY168pQBVgixB/MonProjetSup?node-id=4245-54342&t=bxHKkzIDspv3RPLY-4

Le lien:

https://dossierappel.parcoursup.fr/Candidats/public/fiches/afficherFicheFormation?g_ta_cod=6115&typeBac=0&originePc=0

originePc doit rester égal à 0
typeBac = 
Bac général= 1
Bac techno= 2
Bac techno= 3
Autres = 0

Le typeBac est renseigné dans la table ref_baccalaureat champ 'id_carte_parcoursup'

Pour le bouton : https://www.radix-ui.com/primitives/docs/components/toggle

**Comment by Maxgux** [comment]
Ca demande de retoucher pas mal le composant. Pas un petit sujet :)

**Comment by Numero7** [comment]
@aureliadelzottoOCTO @Maxgux top merci
