### ISSUE TITLE
Appel à /formations avec un id de métier

### ISSUE THREAD

**Issue by aureliadelzottoOCTO** [betagouv/monprojetsup#633]
## Description du bug
Un appel à /formation est fait avec un id de métier

## Reproduire le bug

- Insérer en base ce profil (un profil avec des métiers en favoris)
_Exemple_
`INSERT INTO public.profil_eleve (situation, classe, id_baccalaureat, specialites, domaines, centres_interets, metiers_favoris, duree_etudes_prevue, alternance, communes_favorites, moyenne_generale, corbeille_formations, formations_favorites, id) VALUES ('AUCUNE_IDEE', 'TERMINALE', 'Générale', '{mat701,mat1061}', '{dom2,dom39}', '{ci6,ci21}', '{MET.930,MET.445,MET.234,MET.265}', 'INDIFFERENT', 'PAS_INTERESSE', '[{"nom": "Paris", "latitude": 48.859, "codeInsee": "75056", "longitude": 2.347}]', -1, '{}', '[{"idFormation": "fl2012", "priseDeNote": null, "voeuxChoisis": [], "niveauAmbition": 0}, {"idFormation": "fl33", "priseDeNote": null, "voeuxChoisis": [], "niveauAmbition": 0}, {"idFormation": "fl649", "priseDeNote": null, "voeuxChoisis": [], "niveauAmbition": 0}, {"idFormation": "fl31", "priseDeNote": null, "voeuxChoisis": [], "niveauAmbition": 0}, {"idFormation": "fl17", "priseDeNote": null, "voeuxChoisis": [], "niveauAmbition": 0}, {"idFormation": "fr22", "priseDeNote": null, "voeuxChoisis": [], "niveauAmbition": 0}]', '44b414b4-223e-4782-ab2b-1819161405e7');`
- Aller sur l'onglet **Métier** dans **Consulter ma sélection**
- Revenir à la page **Explorer les formations**

**Comment by Maxgux** [comment]
J'ai fait pas mal de modifs à cette partie du code et je ne reproduis pas le problème. Si tu le retrouves on en reparle :)

**Comment by Numero7** [comment]
solved en attendant une preuve du contraire
