### ISSUE TITLE
affichage de villes dans lesquelles la formation n'est pas dispo

### ISSUE THREAD

**Issue by Numero7** [betagouv/monprojetsup#637]
Je ne pense pas qu'il y ait un Bachelor ingénieur à Pauillac?

![Image](https://github.com/user-attachments/assets/966edfc1-9de4-4a49-9b04-f0a365a6d829)

Utiliser le gta_code pour récuperer la ville plutôt

**Comment by Maxgux** [comment]
C'est un bug back du coup ? @aureliadelzottoOCTO

**Comment by Numero7** [comment]
@aureliadelzottoOCTO 

Règles métiers pour afficher "Formations disponibles dans N villes  dont ville_1,ville_2,ville_3"

Calculer la liste L1 des voeux disponibles via la jointure ref_join_ville_voeu pour cette formation.
Calculer la liste  L2 des code_commune  correspondants.
Si L2 est vide, ne rien afficher.
Sinon, N = la taille de L2

Pour chaque élément dans L2, calculer la distance aux préférences géographiques via la table ref_join_ville_voeu.
Pour cela, pour une commune C donnée de L2, calculer le min des distances (C,V) pour V une ville apparaissant dans les préférences géographiques.
Trier L2 par ordre décroissant de distance aux préférences.

Alors ville_1, ville_2, ville_3 sont les trois premiers éléments de L2 (ou moins si L2 est de taille < 3).

**Comment by Numero7** [comment]
@aureliadelzottoOCTO c'est nickel merci
