### ISSUE TITLE
Remettre de la couleur au niveau des vœux favoris

### ISSUE THREAD

**Issue by Numero7** [betagouv/monprojetsup#703]
Ce serait mieux d'avoir le coeu ren rouge et le logo parcoursup aux couleurs habituelles

![Image](https://github.com/user-attachments/assets/e2144dc6-0ff0-4e76-809f-79b6dd7d43e1)

**Comment by Maxgux** [comment]
@Numero7 Le logo Parcoursup en gris c'est pour préciser qu'on ne peut pas l'enlever (effet bouton désactivé). Tu veux quand même le mettre aux couleurs Parcoursup?

**Comment by Numero7** [comment]
> @Numero7 Le logo Parcoursup en gris c'est pour préciser qu'on ne peut pas l'enlever (effet bouton désactivé). Tu veux quand même le mettre aux couleurs Parcoursup?

@Maxgux yes stp

**Comment by Numero7** [comment]
@Maxgux aller je pinaille.

On ne peut pas avoir exactement le svg afin de reconnaître le code couleur psup? Actuellement on voit ça

 ![Image](https://github.com/user-attachments/assets/d8ebb429-ec02-4f32-9f02-31ce7b865b01)

mais le svg initial resemble à ça

![Image](https://github.com/user-attachments/assets/c862c8b7-1692-462b-9b08-882ac78aa0a1)

**Comment by Numero7** [comment]
c'est bon, merci
